@Library('jarvis@advanced-jenkins') _

// 3.01-jenkins-pipeline
pipeline {
    agent any

    stages {
        // 3.02-jenkins-app-build
        stage('📦 Build Quarkus app ⚡️') {
            steps {
                echo '📦 Build Quarkus app ⚡️'
                dir('jarvis-app') {
                    sh 'mvn clean package'
                }
            }
        }
        // 3.03-jenkins-docker-build
        stage('🐳 Build Docker image 🐳') {
            steps {
                echo '🐳 Build Docker image 🐳'
                dir('jarvis-app') {
                    script {
                        docker.withRegistry('https://95y036e0.gra7.container-registry.ovh.net/devoxx', 'harbor') {
                            def image = docker.build('95y036e0.gra7.container-registry.ovh.net/devoxx/jarvis-app', '-f src/main/docker/Dockerfile.jvm .')
                            image.push("v${env.BUILD_NUMBER}")
                        }
                    }
                }
            }
        }
        // 3.04-jenkins-github-tag
        stage('🏷️ Tag et Push dans GitHub 🐙') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'gh-token', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                        jarvis.ghTag(GIT_USERNAME, GIT_PASSWORD, BUILD_NUMBER)
                    }
                }
            }
        }
        // 3.05-jenkins-github-release
        stage('🪪 Release GitHub 🪪') {
            steps {
               script {
                   withCredentials([usernamePassword(credentialsId: 'gh-token',  usernameVariable: 'GIT_USERNAME', passwordVariable: 'GITHUB_TOKEN')]) {
                        jarvis.ghRelease(GIT_USERNAME, GITHUB_TOKEN, BUILD_NUMBER)
                     }
                }
            }
        }
    }
    // 3.06-jenkins-post-pipeline
    post {
        success {
            echo '✅ Déploiement réussi ! 🤩'
        }
        failure {
            echo '❌ Échec du déploiement 😭'
        }
    }
}
