apiVersion: v1
kind: Service
metadata:
  labels:
    app: ovh-lb
  name: ovh-lb-service
  annotations:
    loadbalancer.ovhcloud.com/class: octavia 
    loadbalancer.ovhcloud.com/flavor: small
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
      app.kubernetes.io/name: jarvis-operator
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: LoadBalancer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: service-deployment-cluster-role
    namespace: jarvis-operator
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    - serviceaccounts
    - services  
    verbs:
    - "*"
  - apiGroups:
    - "apps"
    verbs:
        - "*"
    resources:
    - deployments
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-deployment-cluster-role-binding
  namespace: jarvis-operator
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: service-deployment-cluster-role
subjects:
  - kind: ServiceAccount
    name: jarvis-operator
    namespace: jarvis-operator
---